pipeline {
  agent {
    docker {
      image 'cypress/base:10'
      args '-p 3000:3000'
    }
  }

  environment {
    CI = 'true'
  }

  stages {
    stage('Build') {
      steps {
            sh 'npm install'
      }
    }

    stage('Test') {
      steps {
        sh './jenkins/scripts/1_test.sh'
      }
    }

    stage('Deliver') {
      steps {
        sh './jenkins/scripts/2_deliver.sh'
        input message: 'Finished using the web site? (Click "Proceed" to continue)'
        sh './jenkins/scripts/3_kill.sh'
      }
    }
  }
}